name: osscompliance

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      
    - name: Generate SBOM
      uses: CycloneDX/gh-gomod-generate-sbom@v1
      with:
       version: v1
       args: mod -licenses -json -output bom.json
